name: Check change
on:
  pull_request:

jobs:
  check-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '14'

      - run: yarn

      - run: yarn checkchange
